"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Tijs-B"
email = "14929648+Tijs-B@users.noreply.github.com"

[ui]
default-command = "log"
diff-formatter = "difft"

[template-aliases]
'format_short_signature(signature)' = 'signature.name()'

[merge-tools.pycharm]
program = "/Applications/PyCharm.app/Contents/MacOS/pycharm"
edit-args = ["diff", "$left", "$right"]
merge-args = ["merge", "$right", "$left", "$base", "$output"]
diff-args = ["diff", "$left", "$right"]

[merge-tools.difft]
diff-args = ["--color=always", "$left", "$right"]

################## Local settings ##########################
[[--scope]]
--when.repositories = ["~/code"]

[--scope.fix.tools.1-ruff-format]
command = ["poetry", "run", "ruff", "format", "--stdin-filename", "$path", "-"]
patterns = ["glob:'**/*.py'"]

[--scope.fix.tools.2-ruff-check]
command = [
  "poetry",
  "run",
  "ruff",
  "check",
  "--fix",
  "--stdin-filename",
  "$path",
  "-",
]
patterns = ["glob:'**/*.py'"]

[--scope.fix.tools.3-ruff-format]
command = ["poetry", "run", "ruff", "format", "--stdin-filename", "$path", "-"]
patterns = ["glob:'**/*.py'"]
