"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Tijs-B"
email = "14929648+Tijs-B@users.noreply.github.com"

[ui]
default-command = "log"
diff-formatter = "difft"


[merge-tools.pycharm]
program = "/Applications/PyCharm.app/Contents/MacOS/pycharm"
edit-args = ["diff", "$left", "$right"]
merge-args = ["merge", "$right", "$left", "$base", "$output"]
diff-args = ["diff", "$left", "$right"]

[merge-tools.difft]
diff-args = ["--color=always", "--sort-paths", "$left", "$right"]

[git]
private-commits = "description(glob:'private:*') | description(glob:'wip:*')"

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_pushable(to)' = 'heads(::to & ~description(exact:"") & (~empty() | merges()))'

[aliases]
e = ["edit"]
s = ["squash"]
# Frm: https://github.com/jj-vcs/jj/discussions/5568#discussioncomment-12674748
tug = ["bookmark", "move", "--from", "closest_bookmark(@)", "--to", "closest_pushable(@)"]

################## Visual settings #########################

[template-aliases]
# Only show commiter name in `jj log`
'format_short_signature(signature)' = 'signature.name()'

[templates]
# Show diff in `jj describe` editor (just like commit.verbose in git)
draft_commit_description = '''
concat(
  coalesce(description, default_commit_description, "\n"),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''


################## Local settings ##########################
[[--scope]]
--when.repositories = ["~/code"]

[--scope.fix.tools.1-ruff-format]
command = ["poetry", "run", "ruff", "format", "--stdin-filename", "$path", "-"]
patterns = ["glob:'**/*.py'"]

[--scope.fix.tools.2-ruff-check]
command = [
  "poetry",
  "run",
  "ruff",
  "check",
  "--fix",
  "--stdin-filename",
  "$path",
  "-",
]
patterns = ["glob:'**/*.py'"]

[--scope.fix.tools.3-ruff-format]
command = ["poetry", "run", "ruff", "format", "--stdin-filename", "$path", "-"]
patterns = ["glob:'**/*.py'"]
