# Change position of kubernetes to the end of the first line.
# From https://starship.rs/config/#prompt
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$kubernetes\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$netns\
$shell\
$character"""

[docker_context]
disabled = true

[git_metrics]
disabled = false

[kubernetes]
disabled = false
detect_folders = ['k8s']
format = 'on [$symbol$context( \($namespace\))]($style) '

[[kubernetes.contexts]]
context_pattern = '.*IRE-G-EKS-DEV-1'
style = 'blue'
context_alias = 'eks-dev'

[[kubernetes.contexts]]
context_pattern = '.*IRE-G-EKS-STAGING-1'
style = 'green'
context_alias = 'eks-acc'

[[kubernetes.contexts]]
context_pattern = '.*IRE-G-EKS-PROD-1'
style = 'red'
context_alias = 'eks-prd'

[package]
disabled = true

[python]
format = '(in [${symbol}($virtualenv) ]($style))'

[rust]
disabled = true
